
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    networks:
      - app_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
  
  celery:
    build: .
    command:  celery -A video_processing_system worker -l info -P gevent
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
